/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ParseAbiDataRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-22T20:49:03.474366515Z[Etc/UTC]")
public class ParseAbiDataRequest {
  @SerializedName("chain_id")
  private String chainId = null;

  @SerializedName("contract_address")
  private String contractAddress = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("signer")
  private String signer = null;

  public ParseAbiDataRequest chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

   /**
   * chain_id
   * @return chainId
  **/
  @Schema(example = "56", required = true, description = "chain_id")
  public String getChainId() {
    return chainId;
  }

  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public ParseAbiDataRequest contractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

   /**
   * contract_address
   * @return contractAddress
  **/
  @Schema(example = "489982930986835137684486657990555633941558688085", description = "contract_address")
  public String getContractAddress() {
    return contractAddress;
  }

  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }

  public ParseAbiDataRequest data(String data) {
    this.data = data;
    return this;
  }

   /**
   * data
   * @return data
  **/
  @Schema(example = "38020752995870066111790065015062961812328902090107696250858266643344188923832740441241402799828641949243718670476236652057420675249926299203332389775628687908012032", required = true, description = "data")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public ParseAbiDataRequest signer(String signer) {
    this.signer = signer;
    return this;
  }

   /**
   * signer
   * @return signer
  **/
  @Schema(description = "signer")
  public String getSigner() {
    return signer;
  }

  public void setSigner(String signer) {
    this.signer = signer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParseAbiDataRequest parseAbiDataRequest = (ParseAbiDataRequest) o;
    return Objects.equals(this.chainId, parseAbiDataRequest.chainId) &&
        Objects.equals(this.contractAddress, parseAbiDataRequest.contractAddress) &&
        Objects.equals(this.data, parseAbiDataRequest.data) &&
        Objects.equals(this.signer, parseAbiDataRequest.signer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chainId, contractAddress, data, signer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParseAbiDataRequest {\n");
    
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    signer: ").append(toIndentedString(signer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
