/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseWrapperobjectf7b82021fc934bb69009542c33e30a39Result;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-22T20:45:53.807180373Z[Etc/UTC]")
public class ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("result")
  private ResponseWrapperobjectf7b82021fc934bb69009542c33e30a39Result result = null;

  public ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Code 1：Success
   * @return code
  **/
  @Schema(description = "Code 1：Success")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Response message
   * @return message
  **/
  @Schema(description = "Response message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 result(ResponseWrapperobjectf7b82021fc934bb69009542c33e30a39Result result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public ResponseWrapperobjectf7b82021fc934bb69009542c33e30a39Result getResult() {
    return result;
  }

  public void setResult(ResponseWrapperobjectf7b82021fc934bb69009542c33e30a39Result result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 responseWrapperobjectF7b82021Fc934bb69009542c33e30a39 = (ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39) o;
    return Objects.equals(this.code, responseWrapperobjectF7b82021Fc934bb69009542c33e30a39.code) &&
        Objects.equals(this.message, responseWrapperobjectF7b82021Fc934bb69009542c33e30a39.message) &&
        Objects.equals(this.result, responseWrapperobjectF7b82021Fc934bb69009542c33e30a39.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperobjectF7b82021Fc934bb69009542c33e30a39 {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
