/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Response result
 */
@Schema(description = "Response result")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-22T20:45:53.807180373Z[Etc/UTC]")
public class ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult {
  @SerializedName("website_contract_security")
  private List<String> websiteContractSecurity = null;

  @SerializedName("phishing_site")
  private Integer phishingSite = null;

  public ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult websiteContractSecurity(List<String> websiteContractSecurity) {
    this.websiteContractSecurity = websiteContractSecurity;
    return this;
  }

  public ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult addWebsiteContractSecurityItem(String websiteContractSecurityItem) {
    if (this.websiteContractSecurity == null) {
      this.websiteContractSecurity = new ArrayList<String>();
    }
    this.websiteContractSecurity.add(websiteContractSecurityItem);
    return this;
  }

   /**
   * Get websiteContractSecurity
   * @return websiteContractSecurity
  **/
  @Schema(description = "")
  public List<String> getWebsiteContractSecurity() {
    return websiteContractSecurity;
  }

  public void setWebsiteContractSecurity(List<String> websiteContractSecurity) {
    this.websiteContractSecurity = websiteContractSecurity;
  }

  public ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult phishingSite(Integer phishingSite) {
    this.phishingSite = phishingSite;
    return this;
  }

   /**
   * It means whether the website is a phishing site. \&quot;1\&quot; means true; \&quot;0\&quot; means that we have not found malicious behavior of this website.
   * @return phishingSite
  **/
  @Schema(description = "It means whether the website is a phishing site. \"1\" means true; \"0\" means that we have not found malicious behavior of this website.")
  public Integer getPhishingSite() {
    return phishingSite;
  }

  public void setPhishingSite(Integer phishingSite) {
    this.phishingSite = phishingSite;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult responseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult = (ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult) o;
    return Objects.equals(this.websiteContractSecurity, responseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult.websiteContractSecurity) &&
        Objects.equals(this.phishingSite, responseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult.phishingSite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(websiteContractSecurity, phishingSite);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperMapstringstringa9a4024ae50a4a3aa475dba457d7c10eResult {\n");
    
    sb.append("    websiteContractSecurity: ").append(toIndentedString(websiteContractSecurity)).append("\n");
    sb.append("    phishingSite: ").append(toIndentedString(phishingSite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
