/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Response result
 */
@Schema(description = "Response result")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-22T20:49:03.474366515Z[Etc/UTC]")
public class ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result {
  @SerializedName("{{contract_address}}")
  private ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress contractAddress = null;

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result contractAddress(ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

   /**
   * Get contractAddress
   * @return contractAddress
  **/
  @Schema(description = "")
  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress getContractAddress() {
    return contractAddress;
  }

  public void setContractAddress(ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress contractAddress) {
    this.contractAddress = contractAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result = (ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result) o;
    return Objects.equals(this.contractAddress, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result.contractAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849Result {\n");
    
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
