/*
 * GoPlus Security API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex;
import io.swagger.client.model.ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * contarct address
 */
@Schema(description = "contarct address")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-22T20:45:53.807180373Z[Etc/UTC]")
public class ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress {
  @SerializedName("note")
  private String note = null;

  @SerializedName("lp_total_supply")
  private String lpTotalSupply = null;

  @SerializedName("lp_holders")
  private List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> lpHolders = null;

  @SerializedName("is_airdrop_scam")
  private String isAirdropScam = null;

  @SerializedName("other_potential_risks")
  private String otherPotentialRisks = null;

  @SerializedName("transfer_pausable")
  private String transferPausable = null;

  @SerializedName("trading_cooldown")
  private String tradingCooldown = null;

  @SerializedName("hidden_owner")
  private String hiddenOwner = null;

  @SerializedName("selfdestruct")
  private String selfdestruct = null;

  @SerializedName("owner_percent")
  private String ownerPercent = null;

  @SerializedName("is_whitelisted")
  private String isWhitelisted = null;

  @SerializedName("holder_count")
  private String holderCount = null;

  @SerializedName("trust_list")
  private String trustList = null;

  @SerializedName("is_honeypot")
  private String isHoneypot = null;

  @SerializedName("holders")
  private List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> holders = null;

  @SerializedName("dex")
  private List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex> dex = null;

  @SerializedName("is_open_source")
  private String isOpenSource = null;

  @SerializedName("sell_tax")
  private String sellTax = null;

  @SerializedName("token_name")
  private String tokenName = null;

  @SerializedName("creator_address")
  private String creatorAddress = null;

  @SerializedName("creator_percent")
  private String creatorPercent = null;

  @SerializedName("is_proxy")
  private String isProxy = null;

  @SerializedName("creator_balance")
  private String creatorBalance = null;

  @SerializedName("is_in_dex")
  private String isInDex = null;

  @SerializedName("owner_balance")
  private String ownerBalance = null;

  @SerializedName("total_supply")
  private String totalSupply = null;

  @SerializedName("is_true_token")
  private String isTrueToken = null;

  @SerializedName("can_take_back_ownership")
  private String canTakeBackOwnership = null;

  @SerializedName("is_blacklisted")
  private String isBlacklisted = null;

  @SerializedName("owner_address")
  private String ownerAddress = null;

  @SerializedName("slippage_modifiable")
  private String slippageModifiable = null;

  @SerializedName("buy_tax")
  private String buyTax = null;

  @SerializedName("external_call")
  private String externalCall = null;

  @SerializedName("cannot_sell_all")
  private String cannotSellAll = null;

  @SerializedName("lp_holder_count")
  private String lpHolderCount = null;

  @SerializedName("personal_slippage_modifiable")
  private String personalSlippageModifiable = null;

  @SerializedName("is_anti_whale")
  private String isAntiWhale = null;

  @SerializedName("is_mintable")
  private String isMintable = null;

  @SerializedName("owner_change_balance")
  private String ownerChangeBalance = null;

  @SerializedName("cannot_buy")
  private String cannotBuy = null;

  @SerializedName("anti_whale_modifiable")
  private String antiWhaleModifiable = null;

  @SerializedName("token_symbol")
  private String tokenSymbol = null;

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress note(String note) {
    this.note = note;
    return this;
  }

   /**
   * It describes whether the contract has other things investors need to know.  Example:  \&quot;note”: “Contract owner is a multisign contract.”(Notice:(1) If we haven&#x27;t found any other thing which is valuable yet, there will be no return.  (2) Type: string.)
   * @return note
  **/
  @Schema(description = "It describes whether the contract has other things investors need to know.  Example:  \"note”: “Contract owner is a multisign contract.”(Notice:(1) If we haven't found any other thing which is valuable yet, there will be no return.  (2) Type: string.)")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress lpTotalSupply(String lpTotalSupply) {
    this.lpTotalSupply = lpTotalSupply;
    return this;
  }

   /**
   * It describes the supply number of the LP token. Example:\&quot;lp_total_supply\&quot;: \&quot;100000000\&quot;. No return means no LP.(Notice:(1) When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return.  (2) It is LP token number, NOT token number)
   * @return lpTotalSupply
  **/
  @Schema(description = "It describes the supply number of the LP token. Example:\"lp_total_supply\": \"100000000\". No return means no LP.(Notice:(1) When \"is_in_dex\": \"0\", there will be no return.  (2) It is LP token number, NOT token number)")
  public String getLpTotalSupply() {
    return lpTotalSupply;
  }

  public void setLpTotalSupply(String lpTotalSupply) {
    this.lpTotalSupply = lpTotalSupply;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress lpHolders(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> lpHolders) {
    this.lpHolders = lpHolders;
    return this;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress addLpHoldersItem(ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders lpHoldersItem) {
    if (this.lpHolders == null) {
      this.lpHolders = new ArrayList<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders>();
    }
    this.lpHolders.add(lpHoldersItem);
    return this;
  }

   /**
   * Top10 LP token holders info(Notice:When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return. )
   * @return lpHolders
  **/
  @Schema(description = "Top10 LP token holders info(Notice:When \"is_in_dex\": \"0\", there will be no return. )")
  public List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> getLpHolders() {
    return lpHolders;
  }

  public void setLpHolders(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> lpHolders) {
    this.lpHolders = lpHolders;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isAirdropScam(String isAirdropScam) {
    this.isAirdropScam = isAirdropScam;
    return this;
  }

   /**
   * It describes whether the token is an airdrop scam. \&quot;1\&quot; means true; \&quot;0\&quot; means false; None means no result (Because We did not find conclusive information on whether token is an airdrop scam).(Notice:Only \&quot;is_airdrop_scam\&quot;: \&quot;1\&quot; means it is an airdrop scam.)
   * @return isAirdropScam
  **/
  @Schema(description = "It describes whether the token is an airdrop scam. \"1\" means true; \"0\" means false; None means no result (Because We did not find conclusive information on whether token is an airdrop scam).(Notice:Only \"is_airdrop_scam\": \"1\" means it is an airdrop scam.)")
  public String getIsAirdropScam() {
    return isAirdropScam;
  }

  public void setIsAirdropScam(String isAirdropScam) {
    this.isAirdropScam = isAirdropScam;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress otherPotentialRisks(String otherPotentialRisks) {
    this.otherPotentialRisks = otherPotentialRisks;
    return this;
  }

   /**
   * It describes whether the contract has other potential risks. Example: “other_potential_risks”: “Owner can set different transaction taxes for each user, which can trigger serious losses.”(Notice:(1) If we haven&#x27;t found any other potential risk yet, there will be no return.  (2) Type: string.)
   * @return otherPotentialRisks
  **/
  @Schema(description = "It describes whether the contract has other potential risks. Example: “other_potential_risks”: “Owner can set different transaction taxes for each user, which can trigger serious losses.”(Notice:(1) If we haven't found any other potential risk yet, there will be no return.  (2) Type: string.)")
  public String getOtherPotentialRisks() {
    return otherPotentialRisks;
  }

  public void setOtherPotentialRisks(String otherPotentialRisks) {
    this.otherPotentialRisks = otherPotentialRisks;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress transferPausable(String transferPausable) {
    this.transferPausable = transferPausable;
    return this;
  }

   /**
   * It describes whether trading can be pausable by token contract. \&quot;1\&quot; means true; \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) This feature means that the contract owner will be able to suspend trading at any time, after that anyone will not be able to sell, except those who have special authority.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)
   * @return transferPausable
  **/
  @Schema(description = "It describes whether trading can be pausable by token contract. \"1\" means true; \"0\" means false; No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) This feature means that the contract owner will be able to suspend trading at any time, after that anyone will not be able to sell, except those who have special authority.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)")
  public String getTransferPausable() {
    return transferPausable;
  }

  public void setTransferPausable(String transferPausable) {
    this.transferPausable = transferPausable;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress tradingCooldown(String tradingCooldown) {
    this.tradingCooldown = tradingCooldown;
    return this;
  }

   /**
   * It describes whether the contract has trading-cool-down mechanism which can limits the minimum time between two transactions. \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return. (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return. )
   * @return tradingCooldown
  **/
  @Schema(description = "It describes whether the contract has trading-cool-down mechanism which can limits the minimum time between two transactions. \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return. (2) Sometimes, when \"is_proxy\": \"1\", there will be no return. )")
  public String getTradingCooldown() {
    return tradingCooldown;
  }

  public void setTradingCooldown(String tradingCooldown) {
    this.tradingCooldown = tradingCooldown;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress hiddenOwner(String hiddenOwner) {
    this.hiddenOwner = hiddenOwner;
    return this;
  }

   /**
   * It describes whether the contract has hidden owners. For contract with a hidden owner, developer can still manipulate the contract even if the ownership has been abandoned. “1” means true; \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Hidden owner is often used by developers to hide ownership and is often accompanied by malicious functionality. When the hidden owner exists, it is assumed that ownership has not been abandoned.)
   * @return hiddenOwner
  **/
  @Schema(description = "It describes whether the contract has hidden owners. For contract with a hidden owner, developer can still manipulate the contract even if the ownership has been abandoned. “1” means true; \"0\" means false; No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Hidden owner is often used by developers to hide ownership and is often accompanied by malicious functionality. When the hidden owner exists, it is assumed that ownership has not been abandoned.)")
  public String getHiddenOwner() {
    return hiddenOwner;
  }

  public void setHiddenOwner(String hiddenOwner) {
    this.hiddenOwner = hiddenOwner;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress selfdestruct(String selfdestruct) {
    this.selfdestruct = selfdestruct;
    return this;
  }

   /**
   * It describes whether this contract can self destruct. \&quot;1\&quot; means true;  \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) When the self-destruct function is triggered, this contract will be destroyed, all functions will be unavailable, and all related assets will be erased.)
   * @return selfdestruct
  **/
  @Schema(description = "It describes whether this contract can self destruct. \"1\" means true;  \"0\" means false; No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) When the self-destruct function is triggered, this contract will be destroyed, all functions will be unavailable, and all related assets will be erased.)")
  public String getSelfdestruct() {
    return selfdestruct;
  }

  public void setSelfdestruct(String selfdestruct) {
    this.selfdestruct = selfdestruct;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress ownerPercent(String ownerPercent) {
    this.ownerPercent = ownerPercent;
    return this;
  }

   /**
   * It describes the percentage of tokens held by the contract owner.  Example:\&quot;owner_balance\&quot;: \&quot;0.1\&quot;.  No return or return empty means there is no ownership or can&#x27;t find ownership.(Notice:(1) 1 means 100% here. (2) When \&quot;owner_address\&quot; returns empty, or no return, there will be no return.)
   * @return ownerPercent
  **/
  @Schema(description = "It describes the percentage of tokens held by the contract owner.  Example:\"owner_balance\": \"0.1\".  No return or return empty means there is no ownership or can't find ownership.(Notice:(1) 1 means 100% here. (2) When \"owner_address\" returns empty, or no return, there will be no return.)")
  public String getOwnerPercent() {
    return ownerPercent;
  }

  public void setOwnerPercent(String ownerPercent) {
    this.ownerPercent = ownerPercent;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isWhitelisted(String isWhitelisted) {
    this.isWhitelisted = isWhitelisted;
    return this;
  }

   /**
   * It describes whether the whitelist function is not included in the contract. If there is a whitelist, some addresses may not be able to trade normally. \&quot;1\&quot; means true; \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Whitelisting is mostly used to allow specific addresses to make early transactions, tax-free, and not affected by transaction suspension. (4) For contracts without an owner (or the owner is a black hole address), the whitelist will not be able to get updated. However, the existing whitelist is still in effect.)
   * @return isWhitelisted
  **/
  @Schema(description = "It describes whether the whitelist function is not included in the contract. If there is a whitelist, some addresses may not be able to trade normally. \"1\" means true; \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Whitelisting is mostly used to allow specific addresses to make early transactions, tax-free, and not affected by transaction suspension. (4) For contracts without an owner (or the owner is a black hole address), the whitelist will not be able to get updated. However, the existing whitelist is still in effect.)")
  public String getIsWhitelisted() {
    return isWhitelisted;
  }

  public void setIsWhitelisted(String isWhitelisted) {
    this.isWhitelisted = isWhitelisted;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress holderCount(String holderCount) {
    this.holderCount = holderCount;
    return this;
  }

   /**
   * It describes the number of token holders. Example:\&quot;holder_count\&quot;: \&quot;4342\&quot;
   * @return holderCount
  **/
  @Schema(description = "It describes the number of token holders. Example:\"holder_count\": \"4342\"")
  public String getHolderCount() {
    return holderCount;
  }

  public void setHolderCount(String holderCount) {
    this.holderCount = holderCount;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress trustList(String trustList) {
    this.trustList = trustList;
    return this;
  }

   /**
   * It describes whether the token is a famous and trustworthy one. \&quot;1\&quot; means true; No return no result (Because We did not find conclusive information on whether token is a airdrop scam).(Notice:(1) Only \&quot;trust_list\&quot;: \&quot;1\&quot; means it is a famous and trustworthy token.  (2) No return doesn&#x27;t mean it is risky.)
   * @return trustList
  **/
  @Schema(description = "It describes whether the token is a famous and trustworthy one. \"1\" means true; No return no result (Because We did not find conclusive information on whether token is a airdrop scam).(Notice:(1) Only \"trust_list\": \"1\" means it is a famous and trustworthy token.  (2) No return doesn't mean it is risky.)")
  public String getTrustList() {
    return trustList;
  }

  public void setTrustList(String trustList) {
    this.trustList = trustList;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isHoneypot(String isHoneypot) {
    this.isHoneypot = isHoneypot;
    return this;
  }

   /**
   * It describes whether the token is a honeypot. \&quot;HoneyPot\&quot; means that the token maybe cannot be sold because of the token contract&#x27;s function, Or the token contains malicious code.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Hight risk, definitely scam.)
   * @return isHoneypot
  **/
  @Schema(description = "It describes whether the token is a honeypot. \"HoneyPot\" means that the token maybe cannot be sold because of the token contract's function, Or the token contains malicious code.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Hight risk, definitely scam.)")
  public String getIsHoneypot() {
    return isHoneypot;
  }

  public void setIsHoneypot(String isHoneypot) {
    this.isHoneypot = isHoneypot;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress holders(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> holders) {
    this.holders = holders;
    return this;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress addHoldersItem(ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders holdersItem) {
    if (this.holders == null) {
      this.holders = new ArrayList<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders>();
    }
    this.holders.add(holdersItem);
    return this;
  }

   /**
   * Top10 holders info
   * @return holders
  **/
  @Schema(description = "Top10 holders info")
  public List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> getHolders() {
    return holders;
  }

  public void setHolders(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressLpHolders> holders) {
    this.holders = holders;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress dex(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex> dex) {
    this.dex = dex;
    return this;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress addDexItem(ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex dexItem) {
    if (this.dex == null) {
      this.dex = new ArrayList<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex>();
    }
    this.dex.add(dexItem);
    return this;
  }

   /**
   * It describes Dex information of where the token that can be traded.(Notice:When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be empty array. )
   * @return dex
  **/
  @Schema(description = "It describes Dex information of where the token that can be traded.(Notice:When \"is_in_dex\": \"0\", there will be empty array. )")
  public List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex> getDex() {
    return dex;
  }

  public void setDex(List<ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddressDex> dex) {
    this.dex = dex;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isOpenSource(String isOpenSource) {
    this.isOpenSource = isOpenSource;
    return this;
  }

   /**
   * It describes whether this contract is open source.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false.(Notice:Un-open-sourced contracts may hide various unknown mechanisms and are extremely risky. When the contract is not open source, we will not be able to detect other risk items.)
   * @return isOpenSource
  **/
  @Schema(description = "It describes whether this contract is open source.  \"1\" means true;  \"0\" means false.(Notice:Un-open-sourced contracts may hide various unknown mechanisms and are extremely risky. When the contract is not open source, we will not be able to detect other risk items.)")
  public String getIsOpenSource() {
    return isOpenSource;
  }

  public void setIsOpenSource(String isOpenSource) {
    this.isOpenSource = isOpenSource;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress sellTax(String sellTax) {
    this.sellTax = sellTax;
    return this;
  }

   /**
   * It describes the tax when selling the token.  Example: \&quot;sell_tax\&quot;: 0.1%.  No return means unknown.(Notice:(1) When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sell tax will cause the actual value received when selling a token to be less than expected, and too much buy tax may lead to large losses. (3) When \&quot;sell_tax\&quot;: \&quot;1\&quot;, it means sell-tax is 100% or this token cannot be sold. (4) Sometimes token&#x27;s  trading-cool-down mechanism would affect our sandbox system. When \&quot;trading_cooldown\&quot;: \&quot;1\&quot;, \&quot;sell_tax\&quot; may return \&quot;1\&quot;.)
   * @return sellTax
  **/
  @Schema(description = "It describes the tax when selling the token.  Example: \"sell_tax\": 0.1%.  No return means unknown.(Notice:(1) When \"is_in_dex\": \"0\", there will be no return.  (2) Sell tax will cause the actual value received when selling a token to be less than expected, and too much buy tax may lead to large losses. (3) When \"sell_tax\": \"1\", it means sell-tax is 100% or this token cannot be sold. (4) Sometimes token's  trading-cool-down mechanism would affect our sandbox system. When \"trading_cooldown\": \"1\", \"sell_tax\" may return \"1\".)")
  public String getSellTax() {
    return sellTax;
  }

  public void setSellTax(String sellTax) {
    this.sellTax = sellTax;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress tokenName(String tokenName) {
    this.tokenName = tokenName;
    return this;
  }

   /**
   * Token Name
   * @return tokenName
  **/
  @Schema(description = "Token Name")
  public String getTokenName() {
    return tokenName;
  }

  public void setTokenName(String tokenName) {
    this.tokenName = tokenName;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress creatorAddress(String creatorAddress) {
    this.creatorAddress = creatorAddress;
    return this;
  }

   /**
   * It describes this contract&#x27;s owner address.  Example: \&quot;creator_address\&quot;: \&quot;0x744aF9cBb7606BB040f6FBf1c0a0B0dcBA6385E5\&quot;;
   * @return creatorAddress
  **/
  @Schema(description = "It describes this contract's owner address.  Example: \"creator_address\": \"0x744aF9cBb7606BB040f6FBf1c0a0B0dcBA6385E5\";")
  public String getCreatorAddress() {
    return creatorAddress;
  }

  public void setCreatorAddress(String creatorAddress) {
    this.creatorAddress = creatorAddress;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress creatorPercent(String creatorPercent) {
    this.creatorPercent = creatorPercent;
    return this;
  }

   /**
   * It describes the percentage of tokens held by the contract owner. Example:\&quot;owner_balance\&quot;: 0.1.(Notice:1 means 100% here.)
   * @return creatorPercent
  **/
  @Schema(description = "It describes the percentage of tokens held by the contract owner. Example:\"owner_balance\": 0.1.(Notice:1 means 100% here.)")
  public String getCreatorPercent() {
    return creatorPercent;
  }

  public void setCreatorPercent(String creatorPercent) {
    this.creatorPercent = creatorPercent;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isProxy(String isProxy) {
    this.isProxy = isProxy;
    return this;
  }

   /**
   * It describes whether this contract has a proxy contract.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Most Proxy contracts are accompanied by modifiable implementation contracts, and implementation contracts may contain significant potential risk. When the contract is a Proxy, we will stop detecting other risk items.)
   * @return isProxy
  **/
  @Schema(description = "It describes whether this contract has a proxy contract.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Most Proxy contracts are accompanied by modifiable implementation contracts, and implementation contracts may contain significant potential risk. When the contract is a Proxy, we will stop detecting other risk items.)")
  public String getIsProxy() {
    return isProxy;
  }

  public void setIsProxy(String isProxy) {
    this.isProxy = isProxy;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress creatorBalance(String creatorBalance) {
    this.creatorBalance = creatorBalance;
    return this;
  }

   /**
   * It describes the balance of the contract owner.  Example:\&quot;owner_balance\&quot;: 100000000.
   * @return creatorBalance
  **/
  @Schema(description = "It describes the balance of the contract owner.  Example:\"owner_balance\": 100000000.")
  public String getCreatorBalance() {
    return creatorBalance;
  }

  public void setCreatorBalance(String creatorBalance) {
    this.creatorBalance = creatorBalance;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isInDex(String isInDex) {
    this.isInDex = isInDex;
    return this;
  }

   /**
   * It describes whether the token can be traded on the main Dex. \&quot;1\&quot; means true; \&quot;0\&quot; means false(Notice:It only counts when the token has a marketing pair with mainstream coins/tokens.)
   * @return isInDex
  **/
  @Schema(description = "It describes whether the token can be traded on the main Dex. \"1\" means true; \"0\" means false(Notice:It only counts when the token has a marketing pair with mainstream coins/tokens.)")
  public String getIsInDex() {
    return isInDex;
  }

  public void setIsInDex(String isInDex) {
    this.isInDex = isInDex;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress ownerBalance(String ownerBalance) {
    this.ownerBalance = ownerBalance;
    return this;
  }

   /**
   * It describes the balance of the contract owner.  Example: \&quot;owner_balance\&quot;: \&quot;100000000\&quot;.  No return or return empty means there is no ownership or can&#x27;t find ownership.(Notice:When \&quot;owner_address\&quot; returns empty, or no return, there will be no return.)
   * @return ownerBalance
  **/
  @Schema(description = "It describes the balance of the contract owner.  Example: \"owner_balance\": \"100000000\".  No return or return empty means there is no ownership or can't find ownership.(Notice:When \"owner_address\" returns empty, or no return, there will be no return.)")
  public String getOwnerBalance() {
    return ownerBalance;
  }

  public void setOwnerBalance(String ownerBalance) {
    this.ownerBalance = ownerBalance;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress totalSupply(String totalSupply) {
    this.totalSupply = totalSupply;
    return this;
  }

   /**
   * It describes the supply number of the token. Example:\&quot;total_supply\&quot;: 100000000
   * @return totalSupply
  **/
  @Schema(description = "It describes the supply number of the token. Example:\"total_supply\": 100000000")
  public String getTotalSupply() {
    return totalSupply;
  }

  public void setTotalSupply(String totalSupply) {
    this.totalSupply = totalSupply;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isTrueToken(String isTrueToken) {
    this.isTrueToken = isTrueToken;
    return this;
  }

   /**
   * It describes whether the token is true or fake. \&quot;1\&quot; means true token; \&quot;0\&quot; means fake token; None means no result (Because we did not find decisive information about the truth or falsity)(Notice:Only \&quot;is_true_token\&quot;: \&quot;0\&quot; means it is a fake token.)
   * @return isTrueToken
  **/
  @Schema(description = "It describes whether the token is true or fake. \"1\" means true token; \"0\" means fake token; None means no result (Because we did not find decisive information about the truth or falsity)(Notice:Only \"is_true_token\": \"0\" means it is a fake token.)")
  public String getIsTrueToken() {
    return isTrueToken;
  }

  public void setIsTrueToken(String isTrueToken) {
    this.isTrueToken = isTrueToken;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress canTakeBackOwnership(String canTakeBackOwnership) {
    this.canTakeBackOwnership = canTakeBackOwnership;
    return this;
  }

   /**
   * It describes whether this contract has the function to take back ownership.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Ownership is mostly used to adjust the parameters and status of the contract, such as minting, modification of slippage, suspension of trading, setting blacklsit, etc.  When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, these functions will most likely be disabled.)
   * @return canTakeBackOwnership
  **/
  @Schema(description = "It describes whether this contract has the function to take back ownership.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Ownership is mostly used to adjust the parameters and status of the contract, such as minting, modification of slippage, suspension of trading, setting blacklsit, etc.  When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, these functions will most likely be disabled.)")
  public String getCanTakeBackOwnership() {
    return canTakeBackOwnership;
  }

  public void setCanTakeBackOwnership(String canTakeBackOwnership) {
    this.canTakeBackOwnership = canTakeBackOwnership;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isBlacklisted(String isBlacklisted) {
    this.isBlacklisted = isBlacklisted;
    return this;
  }

   /**
   * It describes whether the blacklist function is not included in the contract. If there is a blacklist, some addresses may not be able to trade normally. \&quot;1\&quot; means true; \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;,  there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) The contract owner may add any address into the blacklist, and the token holder in blacklist will not be able to trade. Abuse of the blacklist function will lead to great risks.  (4) For contracts without an owner (or the owner is a black hole address), the blacklist will not be able to get updated. However, the existing blacklist is still in effect.)
   * @return isBlacklisted
  **/
  @Schema(description = "It describes whether the blacklist function is not included in the contract. If there is a blacklist, some addresses may not be able to trade normally. \"1\" means true; \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\",  there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) The contract owner may add any address into the blacklist, and the token holder in blacklist will not be able to trade. Abuse of the blacklist function will lead to great risks.  (4) For contracts without an owner (or the owner is a black hole address), the blacklist will not be able to get updated. However, the existing blacklist is still in effect.)")
  public String getIsBlacklisted() {
    return isBlacklisted;
  }

  public void setIsBlacklisted(String isBlacklisted) {
    this.isBlacklisted = isBlacklisted;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress ownerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
    return this;
  }

   /**
   * It describes this contract&#x27;s owner address.  Example: \&quot;owner_address\&quot;: \&quot;0x744aF9cBb7606BB040f6FBf1c0a0B0dcBA6385E5\&quot;;  No return means unknown; Return empty means there is no ownership or can&#x27;t find ownership.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Ownership is mostly used to adjust the parameters and status of the contract, such as minting, modification of slippage, suspension of trading, setting blacklist, etc.  When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, these functions will most likely be disabled.)
   * @return ownerAddress
  **/
  @Schema(description = "It describes this contract's owner address.  Example: \"owner_address\": \"0x744aF9cBb7606BB040f6FBf1c0a0B0dcBA6385E5\";  No return means unknown; Return empty means there is no ownership or can't find ownership.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Ownership is mostly used to adjust the parameters and status of the contract, such as minting, modification of slippage, suspension of trading, setting blacklist, etc.  When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, these functions will most likely be disabled.)")
  public String getOwnerAddress() {
    return ownerAddress;
  }

  public void setOwnerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress slippageModifiable(String slippageModifiable) {
    this.slippageModifiable = slippageModifiable;
    return this;
  }

   /**
   * It describes whether the trading tax can be modifiable by token contract. \&quot;1\&quot; means true; \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Token with modifiable tax means that the contract owner can modify the buy tax or sell tax of the token. This may cause some losses, especially since some contracts have unlimited modifiable tax rates, which would make the token untradeable.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)
   * @return slippageModifiable
  **/
  @Schema(description = "It describes whether the trading tax can be modifiable by token contract. \"1\" means true; \"0\" means false; No return means unknown.(Notice:(1) When When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Token with modifiable tax means that the contract owner can modify the buy tax or sell tax of the token. This may cause some losses, especially since some contracts have unlimited modifiable tax rates, which would make the token untradeable.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)")
  public String getSlippageModifiable() {
    return slippageModifiable;
  }

  public void setSlippageModifiable(String slippageModifiable) {
    this.slippageModifiable = slippageModifiable;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress buyTax(String buyTax) {
    this.buyTax = buyTax;
    return this;
  }

   /**
   * It describes the tax when buying the token.  Example: \&quot;buy_tax\&quot;: 0.1%.  No return means unknown.(Notice:(1) When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return.  (2) Buy tax will cause the actual value received when buying a token to be less than expected, and too much buy tax may lead to heavy losses. (3) When \&quot;buy_tax\&quot;: \&quot;1\&quot;, it means buy tax is 100% or cannot buy. (4) Sometimes token&#x27;s anti-bot mechanism would affect our sandbox system, leading to \&quot;cannoy_buy\&quot;: \&quot;1\&quot;,  causing the display of \&quot;buy_tax\&quot;: \&quot;1\&quot;. (5)Some of the token is deisgned not for sale, leading to \&quot;cannot_buy\&quot;:1, causing the display of \&quot;buy_tax\&quot;: \&quot;1\&quot;.)
   * @return buyTax
  **/
  @Schema(description = "It describes the tax when buying the token.  Example: \"buy_tax\": 0.1%.  No return means unknown.(Notice:(1) When \"is_in_dex\": \"0\", there will be no return.  (2) Buy tax will cause the actual value received when buying a token to be less than expected, and too much buy tax may lead to heavy losses. (3) When \"buy_tax\": \"1\", it means buy tax is 100% or cannot buy. (4) Sometimes token's anti-bot mechanism would affect our sandbox system, leading to \"cannoy_buy\": \"1\",  causing the display of \"buy_tax\": \"1\". (5)Some of the token is deisgned not for sale, leading to \"cannot_buy\":1, causing the display of \"buy_tax\": \"1\".)")
  public String getBuyTax() {
    return buyTax;
  }

  public void setBuyTax(String buyTax) {
    this.buyTax = buyTax;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress externalCall(String externalCall) {
    this.externalCall = externalCall;
    return this;
  }

   /**
   * It describes whether the contract would call functions of other contracts when primary methods are executed. \&quot;1\&quot; means true;  \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) External call would cause the implementation of this contract to be highly dependent on other external contracts, which may be a potential risk.)
   * @return externalCall
  **/
  @Schema(description = "It describes whether the contract would call functions of other contracts when primary methods are executed. \"1\" means true;  \"0\" means false; No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) External call would cause the implementation of this contract to be highly dependent on other external contracts, which may be a potential risk.)")
  public String getExternalCall() {
    return externalCall;
  }

  public void setExternalCall(String externalCall) {
    this.externalCall = externalCall;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress cannotSellAll(String cannotSellAll) {
    this.cannotSellAll = cannotSellAll;
    return this;
  }

   /**
   * It describes whether the contract has the function restricting token holder selling all the token.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return.  (2) This feature means that you will not be able to sell all your tokens in a single sale. Sometimes you need to leave a certain percentage of the token, e.g. 10%, sometimes you need to leave a fixed number of token, such as 10 token. (3) When \&quot;buy_tax\&quot;: \&quot;1\&quot;, there will be no return.)
   * @return cannotSellAll
  **/
  @Schema(description = "It describes whether the contract has the function restricting token holder selling all the token.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_in_dex\": \"0\", there will be no return.  (2) This feature means that you will not be able to sell all your tokens in a single sale. Sometimes you need to leave a certain percentage of the token, e.g. 10%, sometimes you need to leave a fixed number of token, such as 10 token. (3) When \"buy_tax\": \"1\", there will be no return.)")
  public String getCannotSellAll() {
    return cannotSellAll;
  }

  public void setCannotSellAll(String cannotSellAll) {
    this.cannotSellAll = cannotSellAll;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress lpHolderCount(String lpHolderCount) {
    this.lpHolderCount = lpHolderCount;
    return this;
  }

   /**
   * It describes the number of LP token holders. Example:\&quot;lp_holder_count\&quot;: \&quot;4342\&quot;. No return means no LP.(Notice:When \&quot;is_in_dex\&quot;: \&quot;0\&quot;, there will be no return.)
   * @return lpHolderCount
  **/
  @Schema(description = "It describes the number of LP token holders. Example:\"lp_holder_count\": \"4342\". No return means no LP.(Notice:When \"is_in_dex\": \"0\", there will be no return.)")
  public String getLpHolderCount() {
    return lpHolderCount;
  }

  public void setLpHolderCount(String lpHolderCount) {
    this.lpHolderCount = lpHolderCount;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress personalSlippageModifiable(String personalSlippageModifiable) {
    this.personalSlippageModifiable = personalSlippageModifiable;
    return this;
  }

   /**
   * It describes whether the owner can set a different tax rate for every assigned address. \&quot;1\&quot; means ture; \&quot;0\&quot; means false; No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;,  there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) The contract owner may set a very outrageous tax rate for assigned address to block it from trading. Abuse of this funtcion will lead to great risks.  (4) For contracts without an owner (or the owner is a black hole address), this function would not able to be used. However, the existing tax rate would be still in effect.)
   * @return personalSlippageModifiable
  **/
  @Schema(description = "It describes whether the owner can set a different tax rate for every assigned address. \"1\" means ture; \"0\" means false; No return means unknown.(Notice:(1) When \"is_open_source\": \"0\",  there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) The contract owner may set a very outrageous tax rate for assigned address to block it from trading. Abuse of this funtcion will lead to great risks.  (4) For contracts without an owner (or the owner is a black hole address), this function would not able to be used. However, the existing tax rate would be still in effect.)")
  public String getPersonalSlippageModifiable() {
    return personalSlippageModifiable;
  }

  public void setPersonalSlippageModifiable(String personalSlippageModifiable) {
    this.personalSlippageModifiable = personalSlippageModifiable;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isAntiWhale(String isAntiWhale) {
    this.isAntiWhale = isAntiWhale;
    return this;
  }

   /**
   * It describes whether the contract has the function to limit the maximum amount of transactions or the maximum token position that for single address.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return. (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return. )
   * @return isAntiWhale
  **/
  @Schema(description = "It describes whether the contract has the function to limit the maximum amount of transactions or the maximum token position that for single address.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return. (2) Sometimes, when \"is_proxy\": \"1\", there will be no return. )")
  public String getIsAntiWhale() {
    return isAntiWhale;
  }

  public void setIsAntiWhale(String isAntiWhale) {
    this.isAntiWhale = isAntiWhale;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress isMintable(String isMintable) {
    this.isMintable = isMintable;
    return this;
  }

   /**
   * It describes whether this contract has the function to mint tokens.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Mint function will directly trigger a massive sell-off, causing the coin price to plummet. It is extremely risky.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)
   * @return isMintable
  **/
  @Schema(description = "It describes whether this contract has the function to mint tokens.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Mint function will directly trigger a massive sell-off, causing the coin price to plummet. It is extremely risky.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)")
  public String getIsMintable() {
    return isMintable;
  }

  public void setIsMintable(String isMintable) {
    this.isMintable = isMintable;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress ownerChangeBalance(String ownerChangeBalance) {
    this.ownerChangeBalance = ownerChangeBalance;
    return this;
  }

   /**
   * It describes whether the contract owner has the authority to change the balance of any token holder.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return.  (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3) Token with this feature means that the owner can modify anyone&#x27;s balance, resulting in an asset straight to zero or a massive minting and sell-off.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)
   * @return ownerChangeBalance
  **/
  @Schema(description = "It describes whether the contract owner has the authority to change the balance of any token holder.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return.  (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3) Token with this feature means that the owner can modify anyone's balance, resulting in an asset straight to zero or a massive minting and sell-off.  (4) This function generally relies on ownership. When the contract does not have an owner (or if the owner is a black hole address) and the owner cannot be retrieved, this function will most likely be disabled.)")
  public String getOwnerChangeBalance() {
    return ownerChangeBalance;
  }

  public void setOwnerChangeBalance(String ownerChangeBalance) {
    this.ownerChangeBalance = ownerChangeBalance;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress cannotBuy(String cannotBuy) {
    this.cannotBuy = cannotBuy;
    return this;
  }

   /**
   * It deiscribes whether the Token can be bought. \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) Generally, \&quot;cannot_buy\&quot;: \&quot;1\&quot; would be found in Reward Tokens. Such Tokens are issued as rewards for some on-chain applications and cannot be bought directly by users. (2) Sometimes token&#x27;s anti-bot mechanism would affect our sandbox system, causing the display of \&quot;buy_tax\&quot;: \&quot;1\&quot;. (3) When “cannot_buy”: \&quot;1\&quot;, our sandbox system might be bloked, causing the display of \&quot;buy_tax\&quot;: \&quot;1\&quot; and \&quot;sell_tax\&quot;: \&quot;1\&quot;)
   * @return cannotBuy
  **/
  @Schema(description = "It deiscribes whether the Token can be bought. \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) Generally, \"cannot_buy\": \"1\" would be found in Reward Tokens. Such Tokens are issued as rewards for some on-chain applications and cannot be bought directly by users. (2) Sometimes token's anti-bot mechanism would affect our sandbox system, causing the display of \"buy_tax\": \"1\". (3) When “cannot_buy”: \"1\", our sandbox system might be bloked, causing the display of \"buy_tax\": \"1\" and \"sell_tax\": \"1\")")
  public String getCannotBuy() {
    return cannotBuy;
  }

  public void setCannotBuy(String cannotBuy) {
    this.cannotBuy = cannotBuy;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress antiWhaleModifiable(String antiWhaleModifiable) {
    this.antiWhaleModifiable = antiWhaleModifiable;
    return this;
  }

   /**
   * It describes whether the contract has the function to modify the maximum amount of transactions or the maximum token position.  \&quot;1\&quot; means true;  \&quot;0\&quot; means false;  No return means unknown.(Notice:(1) When \&quot;is_open_source\&quot;: \&quot;0\&quot;, there will be no return. (2) Sometimes, when \&quot;is_proxy\&quot;: \&quot;1\&quot;, there will be no return.  (3)When the anti whale value is set to a very small value, all tradinge would fail.)
   * @return antiWhaleModifiable
  **/
  @Schema(description = "It describes whether the contract has the function to modify the maximum amount of transactions or the maximum token position.  \"1\" means true;  \"0\" means false;  No return means unknown.(Notice:(1) When \"is_open_source\": \"0\", there will be no return. (2) Sometimes, when \"is_proxy\": \"1\", there will be no return.  (3)When the anti whale value is set to a very small value, all tradinge would fail.)")
  public String getAntiWhaleModifiable() {
    return antiWhaleModifiable;
  }

  public void setAntiWhaleModifiable(String antiWhaleModifiable) {
    this.antiWhaleModifiable = antiWhaleModifiable;
  }

  public ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress tokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
    return this;
  }

   /**
   * Token Symbol
   * @return tokenSymbol
  **/
  @Schema(description = "Token Symbol")
  public String getTokenSymbol() {
    return tokenSymbol;
  }

  public void setTokenSymbol(String tokenSymbol) {
    this.tokenSymbol = tokenSymbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress = (ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress) o;
    return Objects.equals(this.note, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.note) &&
        Objects.equals(this.lpTotalSupply, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.lpTotalSupply) &&
        Objects.equals(this.lpHolders, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.lpHolders) &&
        Objects.equals(this.isAirdropScam, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isAirdropScam) &&
        Objects.equals(this.otherPotentialRisks, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.otherPotentialRisks) &&
        Objects.equals(this.transferPausable, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.transferPausable) &&
        Objects.equals(this.tradingCooldown, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.tradingCooldown) &&
        Objects.equals(this.hiddenOwner, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.hiddenOwner) &&
        Objects.equals(this.selfdestruct, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.selfdestruct) &&
        Objects.equals(this.ownerPercent, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.ownerPercent) &&
        Objects.equals(this.isWhitelisted, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isWhitelisted) &&
        Objects.equals(this.holderCount, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.holderCount) &&
        Objects.equals(this.trustList, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.trustList) &&
        Objects.equals(this.isHoneypot, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isHoneypot) &&
        Objects.equals(this.holders, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.holders) &&
        Objects.equals(this.dex, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.dex) &&
        Objects.equals(this.isOpenSource, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isOpenSource) &&
        Objects.equals(this.sellTax, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.sellTax) &&
        Objects.equals(this.tokenName, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.tokenName) &&
        Objects.equals(this.creatorAddress, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.creatorAddress) &&
        Objects.equals(this.creatorPercent, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.creatorPercent) &&
        Objects.equals(this.isProxy, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isProxy) &&
        Objects.equals(this.creatorBalance, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.creatorBalance) &&
        Objects.equals(this.isInDex, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isInDex) &&
        Objects.equals(this.ownerBalance, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.ownerBalance) &&
        Objects.equals(this.totalSupply, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.totalSupply) &&
        Objects.equals(this.isTrueToken, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isTrueToken) &&
        Objects.equals(this.canTakeBackOwnership, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.canTakeBackOwnership) &&
        Objects.equals(this.isBlacklisted, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isBlacklisted) &&
        Objects.equals(this.ownerAddress, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.ownerAddress) &&
        Objects.equals(this.slippageModifiable, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.slippageModifiable) &&
        Objects.equals(this.buyTax, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.buyTax) &&
        Objects.equals(this.externalCall, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.externalCall) &&
        Objects.equals(this.cannotSellAll, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.cannotSellAll) &&
        Objects.equals(this.lpHolderCount, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.lpHolderCount) &&
        Objects.equals(this.personalSlippageModifiable, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.personalSlippageModifiable) &&
        Objects.equals(this.isAntiWhale, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isAntiWhale) &&
        Objects.equals(this.isMintable, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.isMintable) &&
        Objects.equals(this.ownerChangeBalance, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.ownerChangeBalance) &&
        Objects.equals(this.cannotBuy, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.cannotBuy) &&
        Objects.equals(this.antiWhaleModifiable, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.antiWhaleModifiable) &&
        Objects.equals(this.tokenSymbol, responseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress.tokenSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(note, lpTotalSupply, lpHolders, isAirdropScam, otherPotentialRisks, transferPausable, tradingCooldown, hiddenOwner, selfdestruct, ownerPercent, isWhitelisted, holderCount, trustList, isHoneypot, holders, dex, isOpenSource, sellTax, tokenName, creatorAddress, creatorPercent, isProxy, creatorBalance, isInDex, ownerBalance, totalSupply, isTrueToken, canTakeBackOwnership, isBlacklisted, ownerAddress, slippageModifiable, buyTax, externalCall, cannotSellAll, lpHolderCount, personalSlippageModifiable, isAntiWhale, isMintable, ownerChangeBalance, cannotBuy, antiWhaleModifiable, tokenSymbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperTaTokenSecurityResponse730b76cb88874c8bbfd0494baf55b849ResultContractAddress {\n");
    
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    lpTotalSupply: ").append(toIndentedString(lpTotalSupply)).append("\n");
    sb.append("    lpHolders: ").append(toIndentedString(lpHolders)).append("\n");
    sb.append("    isAirdropScam: ").append(toIndentedString(isAirdropScam)).append("\n");
    sb.append("    otherPotentialRisks: ").append(toIndentedString(otherPotentialRisks)).append("\n");
    sb.append("    transferPausable: ").append(toIndentedString(transferPausable)).append("\n");
    sb.append("    tradingCooldown: ").append(toIndentedString(tradingCooldown)).append("\n");
    sb.append("    hiddenOwner: ").append(toIndentedString(hiddenOwner)).append("\n");
    sb.append("    selfdestruct: ").append(toIndentedString(selfdestruct)).append("\n");
    sb.append("    ownerPercent: ").append(toIndentedString(ownerPercent)).append("\n");
    sb.append("    isWhitelisted: ").append(toIndentedString(isWhitelisted)).append("\n");
    sb.append("    holderCount: ").append(toIndentedString(holderCount)).append("\n");
    sb.append("    trustList: ").append(toIndentedString(trustList)).append("\n");
    sb.append("    isHoneypot: ").append(toIndentedString(isHoneypot)).append("\n");
    sb.append("    holders: ").append(toIndentedString(holders)).append("\n");
    sb.append("    dex: ").append(toIndentedString(dex)).append("\n");
    sb.append("    isOpenSource: ").append(toIndentedString(isOpenSource)).append("\n");
    sb.append("    sellTax: ").append(toIndentedString(sellTax)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    creatorAddress: ").append(toIndentedString(creatorAddress)).append("\n");
    sb.append("    creatorPercent: ").append(toIndentedString(creatorPercent)).append("\n");
    sb.append("    isProxy: ").append(toIndentedString(isProxy)).append("\n");
    sb.append("    creatorBalance: ").append(toIndentedString(creatorBalance)).append("\n");
    sb.append("    isInDex: ").append(toIndentedString(isInDex)).append("\n");
    sb.append("    ownerBalance: ").append(toIndentedString(ownerBalance)).append("\n");
    sb.append("    totalSupply: ").append(toIndentedString(totalSupply)).append("\n");
    sb.append("    isTrueToken: ").append(toIndentedString(isTrueToken)).append("\n");
    sb.append("    canTakeBackOwnership: ").append(toIndentedString(canTakeBackOwnership)).append("\n");
    sb.append("    isBlacklisted: ").append(toIndentedString(isBlacklisted)).append("\n");
    sb.append("    ownerAddress: ").append(toIndentedString(ownerAddress)).append("\n");
    sb.append("    slippageModifiable: ").append(toIndentedString(slippageModifiable)).append("\n");
    sb.append("    buyTax: ").append(toIndentedString(buyTax)).append("\n");
    sb.append("    externalCall: ").append(toIndentedString(externalCall)).append("\n");
    sb.append("    cannotSellAll: ").append(toIndentedString(cannotSellAll)).append("\n");
    sb.append("    lpHolderCount: ").append(toIndentedString(lpHolderCount)).append("\n");
    sb.append("    personalSlippageModifiable: ").append(toIndentedString(personalSlippageModifiable)).append("\n");
    sb.append("    isAntiWhale: ").append(toIndentedString(isAntiWhale)).append("\n");
    sb.append("    isMintable: ").append(toIndentedString(isMintable)).append("\n");
    sb.append("    ownerChangeBalance: ").append(toIndentedString(ownerChangeBalance)).append("\n");
    sb.append("    cannotBuy: ").append(toIndentedString(cannotBuy)).append("\n");
    sb.append("    antiWhaleModifiable: ").append(toIndentedString(antiWhaleModifiable)).append("\n");
    sb.append("    tokenSymbol: ").append(toIndentedString(tokenSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
